server:
  port: 9090
  use-forward-headers: true
  undertow:
    io-threads: 2
    worker-threads: 32
    buffer-size: 1024
    directBuffers: true
spring:
  devtools:
    enabled: true
  cache:
    type: ehcache
    ehcache:
      config: classpath:ehcache.xml
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  freemarker:
    template-loader-path:
      - classpath:/templates
      - file:${site.location}/storage/templates
    cache: false
    check-template-location: true
    charset: utf-8
    settings:
      classic_compatible: true #处理空值
      template_exception_handler: rethrow
      template_update_delay: 0
      datetime_format: yyyy-MM-dd HH:mm
      number_format: 0.##
      auto_import: /utils.ftl as utils
  flyway:
    enabled: false
    baseline-on-migrate: true
    encoding: UTF-8
    locations: classpath:scripts/migration
  datasource:
    #schema: classpath*:scripts/schema.sql
    #continue-on-error: false
    #sql-script-encoding: utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/mblog?useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 123456
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate.format_sql: true
      hibernate.naming.physical-strategy: org.hibernate.scripts.model.naming.PhysicalNamingStrategyStandardImpl
      hibernate.cache.use_second_level_cache: false
      hibernate.search.default.directory_provider: filesystem
      hibernate.search.default.indexBase: ${site.location}/storage/indexes
#安全框架
shiro:
  web:
    enabled: true
  annotations:
    enabled: false
  loginUrl: /login
  successUrl: /index
  unauthorizedUrl: /error/reject.html
  sessionManager:
    cookie:
      maxAge: 604800
  rememberMeManager:
    cookie:
      maxAge: 604800
logging:
  level:
    org.springframework: WARN
    org.hibernate: WARN

# site.options.theme: [default|classic]
site:
  version: 3.5.0
  location: ${user.dir}
  controls:
    # 注册开关
    register: false
    # 注册开启邮箱验证
    register_email_validate: false
    # 发布文章开关
    post: true
    # 评论开关
    comment: false
  options:
    theme: classic
    site_logo: /dist/images/logo/logo.png
    site_favicon: /dist/images/logo/m.png
    storage_max_width: 800
    storage_limit_size: 2
    editor: markdown
    thumbnail_channel_size: 200x112
    thumbnail_post_size: 360x200
